### ISSUE TITLE
ocdatefield output

### ISSUE THREAD

**Issue by jrogalski** [Four51Repositories/OrderCloud-SpecForms#2]
The pageflex output using the ocdatefield is not as expected.

When using the following: 
<ocdatefield customfield="Variant.Specs.Variable6" format="dd-MM-yyyy"></ocdatefield>

The format will appear correctly in the form, but when the job is rendered, the output will appear as:
mm/dd/yyyy 00:00:00

Users will expect the output to appear as how they set the format.

**Comment by ghost** [comment]
could you please leave the product ID of the product you are testing with on these issues?

**Comment by jrogalski** [comment]
Admin: _SKI TEST SITE
Buyer: SKI 2.0
Product ID: OCDirectivesTest

**Comment by ghost** [comment]
Issue should be resolved. Value is now assigned to a string value via an angular filter. The value is then set back to a date object to set the datefield on page load when editing an existing variant.
