### ISSUE TITLE
octimefield output

### ISSUE THREAD

**Issue by jrogalski** [Four51Repositories/OrderCloud-SpecForms#3]
The pageflex output using the octimefield is not as expected.

When using the following: 
<octimefield customfield="Variant.Specs.Variable7"></octimefield>

The format will appear correctly in the form, but when the job is rendered, the output will appear as:
mm/dd/yyyy 00:00:00

Users will expect the output to appear as the time only. ex: 5:30 PM

**Comment by jrogalski** [comment]
Admin: _SKI TEST SITE
Buyer: SKI 2.0
Product ID: OCDirectivesTest

**Comment by ghost** [comment]
Same fix as the other, just applied to a different directive.
